name = "odysseus-ai"
main = "src/worker.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

# Serve Vite frontend build output as static assets
[assets]
directory = "./dist"

[ai]
binding = "AI"
